spring:
  application:
    name: api-gateway
server:
  port: 40000

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/, http://localhost:10001/eureka/

zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /userService/**
      serviceId: service-consumer
    oauth:
      path: /oauthService/**
      serviceId: oauth-server

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:40000/oauthService/oauth/token
      userAuthorizationUri: http://localhost:40000/oauthService/oauth/authorize
      clientId: webapp
    resource:
      userInfoUri: http://localhost:40000/oauthService/user
      preferTokenInfo: false