spring:
  application:
    name: api-gateway
server:
  port: 40000

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/, http://localhost:10001/eureka/

zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /userService/**
      serviceId: service-consumer
    oauth:
      sensitiveHeaders:
      path: /oauthService/**
      serviceId: oauth-server
      stripPrefix: false
  addProxyHeaders: true

security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://localhost:60000/oauth/token
      userAuthorizationUri: http://localhost:60000/oauth/authorize
      clientId: client
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:60000/user
      preferTokenInfo: false

logging:
  level.org.springframework.security: DEBUG