spring:
  application:
    name: oauth-server
server:
  port: 50001

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/, http://localhost:10001/eureka/

security:
  oauth2:
    resource:
      filterOrder: 3