spring:
  application:
    name: oauth-server
server:
  port: 60000

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/, http://localhost:10001/eureka/

logging:
  level.org.springframework.security: DEBUG